use std::io::Cursor;

use opencadcodec::{DwgReader, EntityType};

// Generated by AutoCAD 2025 using BlockNamesFixtures.cs. Named blocks between
// anonymous definitions must consume BLOCK_CONTROL ordinals as well.
#[test]
fn autocad_anonymous_names_preserve_definition_and_insert_identity() {
    let bytes = include_bytes!("anonymous-names.dwg");
    let doc = DwgReader::from_stream(Cursor::new(bytes.as_slice()))
        .read()
        .unwrap();
    for (handle, name) in [
        (0x78, "NamedBefore"),
        (0x7f, "*U2"),
        (0x86, "NamedBetween"),
        (0x8d, "*U4"),
        (0x94, "*U5"),
    ] {
        let block = doc
            .block_records
            .iter()
            .find(|block| block.handle.value() == handle)
            .unwrap();
        assert_eq!(block.name, name);
        let inserts: Vec<_> = doc
            .entities()
            .filter_map(|entity| match entity {
                EntityType::Insert(insert) if insert.block_name == name => Some(insert),
                _ => None,
            })
            .collect();
        assert_eq!(inserts.len(), 1, "INSERT must resolve to {name}");
        assert_eq!(inserts[0].attributes.len(), 1);
        assert_eq!(inserts[0].attributes[0].tag, "TAG");
    }
}
